---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(scales)
library(ggpubr)
```

```{r}
dd <- read_csv('niche_metrics.csv')
dd
```




```{r}
ggplot(data = dd, aes(colour = presence_ratio, x = pc2, y = pc1, size = species_count)) + geom_point()
```
```{r}
gg <- function(gg) {
  gg + geom_point() + theme_bw() + scale_colour_continuous(trans = 'reverse') + labs(color="Presence Ratio", size="Species in Niche")
}
niches <- ggarrange(
  ncol = 2,
  nrow = 2,
  gg(ggplot(dd, aes(x = pc1, y = pc3, colour = presence_ratio, size = species_count)) + ylab("Short Tail + Pointy Beak -> Long Tail + Stubby Beak")) + theme(legend.position="none", axis.title.x=element_blank()),
  gg(ggplot(dd, aes(x = pc2, y = pc3, colour = presence_ratio, size = species_count))) + theme(legend.position="none", axis.title.x=element_blank(), axis.title.y=element_blank()),
  gg(ggplot(dd, aes(x = pc1, y = pc4, colour = presence_ratio, size = species_count)) + ylab("Long Tail + Pointy Beak -> Short Tail + Stubby Beak") + xlab("Body Size")) + theme(legend.position="none"),
  gg(ggplot(dd, aes(x = pc2, y = pc4, colour = presence_ratio, size = species_count)) + xlab("Beak Size")) + theme(legend.position="none", axis.title.y=element_blank()),
  common.legend = T
)
pp <- annotate_figure(niches, top = text_grob("Niche Presence based on Mean Morphology", face = "bold", size = 14))
pp
```



```{r}
jpeg("niches_metrics.jpg", width = 1024, height = 1024)
pp
dev.off()
```