---
title: "Percentage of Regional Richness"
output: html_notebook
---

Run 'download_data.Rmd` First!

```{r setup}
options(na.action = "na.fail") 

library(tidyverse)
library(dplyr)

source("./helper__dredge_functions.R")
```

```{r}
model_average_richness <- function(data) {
  model_average(percentage_of_regional_pool_present ~ mean_elevation_scaled + elevation_delta_scaled + closed_forest + cultivated + herbaceous_vegetation + herbaceous_wetland + open_forest + permanent_water + shrubs + urban + realm + (1|city_name), data, 4)
}
```

----------------------
Find city predictors
----------------------

```{r}
create_city_dataset <- function(mixed_model) {
  city_coeefs <- ranef(mixed_model)$city_name
  city_coeefs <- cbind(city_name = rownames(city_coeefs), city_coeefs)
  rownames(city_coeefs) <- NULL
  names(city_coeefs) <- c('name', 'response')
  
  left_join(city_coeefs, city_data)
}
```

----------------------
Merlin: Difference in richness
----------------------
```{r, cache = TRUE}
merlin_richness_result <- model_average_richness(merlin)
merlin_richness_result
```

```{r}
merlin_mixed_model <- lmer(percentage_of_regional_pool_present ~ mean_elevation_scaled + elevation_delta_scaled + closed_forest + cultivated + herbaceous_vegetation + herbaceous_wetland + open_forest + permanent_water + shrubs + realm + (1|city_name), merlin)
r.squaredGLMM(merlin_mixed_model)
```

```{r}
merlin_fixed_model <- lm(percentage_of_regional_pool_present ~ mean_elevation_scaled + elevation_delta_scaled + closed_forest + cultivated + herbaceous_vegetation + herbaceous_wetland + open_forest + permanent_water + shrubs + realm, merlin)
anova(merlin_mixed_model, merlin_fixed_model)
```

```{r}
anova(merlin_mixed_model, lm(percentage_of_regional_pool_present ~ city_name, merlin))
```


```{r}
merlin_richness_sum <- model_summary('merlin', 'richness', merlin_richness_result)
merlin_richness_sum
```

```{r}
merlin_city_response <- create_city_dataset(merlin_mixed_model)
merlin_city_response[order(merlin_city_response$response), c('name', 'response')]
```

```{r}
write_csv(merlin_city_response[, c('name', 'response')], 'percentage_of_regional_richness__output__merlin_city_richness_intercept.csv')
```


```{r}
summary(merlin_mixed_model)
```

```{r}
merlin_richness_plot <- merlin_richness_sum[merlin_richness_sum$model == 'full',]
merlin_richness_plot$explanatory <- factor(merlin_richness_plot$explanatory, levels = c('closed_forest', 'open_forest', 'shrubs', 'herbaceous_vegetation', 'herbaceous_wetland', 'permanent_water', 'cultivated', 'urban', 'mean_elevation_scaled', 'elevation_delta_scaled', 'realmAfrotropic', 'realmAustralasia', 'realmIndomalayan', 'realmNearctic', 'realmNeotropic'))
merlin_richness_plot$type <- 'Proportion of landcover\n5 km around site'
merlin_richness_plot$type[merlin_richness_plot$explanatory %in% c('mean_elevation_scaled', 'elevation_delta_scaled')] <- 'Scaled (0-1) average\nelevation 5 km around site'
merlin_richness_plot$type[merlin_richness_plot$explanatory %in% c('realmAfrotropic', 'realmAustralasia', 'realmIndomalayan', 'realmNearctic', 'realmNeotropic')] <- 'Realm'

ggplot(merlin_richness_plot, aes(y=explanatory, x=richness_merlin_estimate, colour = type)) + 
  geom_line() +
  geom_point()+
  geom_errorbar(aes(xmin=richness_merlin_estimate-richness_merlin_error, xmax=richness_merlin_estimate+richness_merlin_error), width=.2,
                 position=position_dodge(0.05)) +
  scale_y_discrete(
    limits = rev(levels(merlin_richness_plot$explanatory)), 
    labels = c('closed_forest' = 'Closed forest', 'open_forest' = 'Open forest', 'shrubs' = 'Shrubs', 'herbaceous_vegetation' = 'Herbaceous\nvegetation', 'herbaceous_wetland' = 'Herbaceous\nwetland', 'permanent_water' = 'Permanent\nwater', 'cultivated' = 'Cultivated', 'urban' = 'Urban', 'mean_elevation_scaled' = 'Mean elevation\nscaled', 'elevation_delta_scaled' = 'Elevation delta\nscaled', 'realmAfrotropic' = 'Afrotropical', 'realmAustralasia' = 'Austaliasian', 'realmIndomalayan' = 'Indomalayan', 'realmNearctic' = 'Nearctic', 'realmNeotropic' = 'Neotropical')) +
  theme_bw() +
  geom_vline(xintercept=0, linetype="dotted") +
  guides(colour=guide_legend(title="Predictor type")) + xlab('Increase in proportion of regional richness\n± Standard Error') + ylab('Predictor') +
  theme(legend.justification = "top")

ggsave('percentage_of_regional_pool__output__merlin_richness_result.jpg')
```


----------------------
Birdlife: Difference in richness
----------------------
```{r, cache = TRUE}
bl_richness_result <- model_average_richness(birdlife)
bl_richness_result
```

```{r}
birdlife_mixed_model <- lmer(percentage_of_regional_pool_present ~ mean_elevation_scaled + closed_forest + cultivated + herbaceous_vegetation + herbaceous_wetland + open_forest + shrubs + realm + (1|city_name), birdlife)
r.squaredGLMM(birdlife_mixed_model)
```

```{r}
summary(birdlife_mixed_model)
```

```{r}
birdlife_fixed_model <- lm(percentage_of_regional_pool_present ~ mean_elevation_scaled + closed_forest + cultivated + herbaceous_vegetation + herbaceous_wetland + open_forest + shrubs + realm, birdlife)
anova(birdlife_mixed_model, birdlife_fixed_model)
```

```{r}
summary(birdlife_fixed_model)
```

```{r}
birdlife_city_response <- create_city_dataset(birdlife_mixed_model)
birdlife_city_response[order(birdlife_city_response$response), c('name', 'response')]
```

```{r}
write_csv(birdlife_city_response[, c('name', 'response')], 'percentage_of_regional_richness__output__birdlife_city_richness_intercept.csv')
```


```{r}
bl_richness_sum <- model_summary('birdlife', 'richness', bl_richness_result)
bl_richness_sum
```

```{r}
summary(birdlife_mixed_model)
```

```{r}
birdlife_richness_plot <- bl_richness_sum[bl_richness_sum$model == 'full',]
birdlife_richness_plot$explanatory <- factor(birdlife_richness_plot$explanatory, levels = c('closed_forest', 'open_forest', 'shrubs', 'herbaceous_vegetation', 'herbaceous_wetland', 'permanent_water', 'cultivated', 'urban', 'mean_elevation_scaled', 'elevation_delta_scaled', 'realmAfrotropic', 'realmAustralasia', 'realmIndomalayan', 'realmNearctic', 'realmNeotropic'))
birdlife_richness_plot$type <- 'Proportion of landcover\n5 km around site'
birdlife_richness_plot$type[birdlife_richness_plot$explanatory %in% c('mean_elevation_scaled', 'elevation_delta_scaled')] <- 'Scaled (0-1) average\nelevation 5 km around site'
birdlife_richness_plot$type[birdlife_richness_plot$explanatory %in% c('realmAfrotropic', 'realmAustralasia', 'realmIndomalayan', 'realmNearctic', 'realmNeotropic')] <- 'Realm'

birdlife_plot = ggplot(birdlife_richness_plot, aes(y=explanatory, x=richness_birdlife_estimate, colour = type)) + 
  geom_line() +
  geom_point()+
  geom_errorbar(aes(xmin=richness_birdlife_estimate-richness_birdlife_error, xmax=richness_birdlife_estimate+richness_birdlife_error), width=.2,
                 position=position_dodge(0.05)) +
  scale_y_discrete(
    limits = rev(levels(birdlife_richness_plot$explanatory)), 
    labels = c('closed_forest' = 'Closed forest', 'open_forest' = 'Open forest', 'shrubs' = 'Shrubs', 'herbaceous_vegetation' = 'Herbaceous\nvegetation', 'herbaceous_wetland' = 'Herbaceous\nwetland', 'permanent_water' = 'Permanent\nwater', 'cultivated' = 'Cultivated', 'urban' = 'Urban', 'mean_elevation_scaled' = 'Mean elevation\nscaled', 'elevation_delta_scaled' = 'Elevation delta\nscaled', 'realmAfrotropic' = 'Afrotropical', 'realmAustralasia' = 'Austaliasian', 'realmIndomalayan' = 'Indomalayan', 'realmNearctic' = 'Nearctic', 'realmNeotropic' = 'Neotropical')) +
  theme_bw() +
  geom_vline(xintercept=0, linetype="dotted") +
  guides(colour=guide_legend(title="Predictor type")) + xlab('Increase in proportion of regional pool richness\n± Standard Error') + ylab('Predictor') +
  theme(legend.justification = "top")
birdlife_plot
ggsave('percentage_of_regional_pool__output__birdlife_richness_result.jpg')
```



----------------------
Both: Difference in richness
----------------------
```{r, cache = TRUE}
both_richness_result <- model_average_richness(both)
both_richness_result
```

```{r}
both_mixed_model <- lmer(percentage_of_regional_pool_present ~ mean_elevation_scaled + elevation_delta_scaled + closed_forest + cultivated + herbaceous_vegetation + herbaceous_wetland + open_forest + permanent_water + shrubs + realm + (1|city_name), both)
r.squaredGLMM(both_mixed_model)
```

```{r}
both_fixed_model <- lm(percentage_of_regional_pool_present ~ mean_elevation_scaled + elevation_delta_scaled + closed_forest + cultivated + herbaceous_vegetation + herbaceous_wetland + open_forest + permanent_water + shrubs + realm, both)
anova(both_mixed_model, both_fixed_model)
```

```{r}
both_richness_sum <- model_summary('both', 'richness', both_richness_result)
both_richness_sum
```

```{r}
both_city_response <- create_city_dataset(both_mixed_model)
both_city_response[order(both_city_response$response), c('name', 'response')]
```

```{r}
write_csv(both_city_response[, c('name', 'response')], 'percentage_of_regional_richness__output__both_city_richness_intercept.csv')
```

----------------------
Either: Difference in richness
----------------------
```{r, cache = TRUE}
either_richness_result <- model_average_richness(either)
either_richness_result
```

```{r}
either_mixed_model <- lmer(percentage_of_regional_pool_present ~ mean_elevation_scaled + closed_forest + cultivated + herbaceous_vegetation + herbaceous_wetland + open_forest + permanent_water + shrubs + realm + (1|city_name), either)
r.squaredGLMM(either_mixed_model)
```

```{r}
either_fixed_model <- lm(percentage_of_regional_pool_present ~ mean_elevation_scaled + closed_forest + cultivated + herbaceous_vegetation + herbaceous_wetland + open_forest + permanent_water + shrubs + realm, either)
anova(either_mixed_model, either_fixed_model)
```

```{r}
either_richness_sum <- model_summary('either', 'richness', either_richness_result)
either_richness_sum
```

```{r}
either_city_response <- create_city_dataset(either_mixed_model)
either_city_response[order(either_city_response$response), c('name', 'response')]
```

```{r}
write_csv(either_city_response[, c('name', 'response')], 'percentage_of_regional_richness__output__either_city_richness_intercept.csv')
```

----------------------
Full result
----------------------
```{r}
richness_all <- full_join(full_join(merlin_richness_sum, bl_richness_sum), full_join(both_richness_sum, either_richness_sum))
write_csv(richness_all, "percentage_of_regional_richness__output__richness_result.csv")
richness_all
```


---------------------------------------
Additional figures
---------------------------------------

```{r}
library(tidyr)
library(ggplot2)
library(ggpubr)
```

```{r}
environment <- merlin[,c('closed_forest', 'cultivated', 'herbaceous_vegetation', 'herbaceous_wetland', 'open_forest', 'permanent_water', 'shrubs', 'urban')]
names(environment) <- c('Closed Forest', 'Cultivated', 'Herbaceous Vegetation', 'Herbaceous Wetland', 'Open Forest', 'Permanent Water', 'Shurbs', 'Urban')
landcover <- gather(environment, landcover, proportion)

ggplot(landcover, aes(x = landcover, y = proportion)) + geom_boxplot() + xlab('Landcover Class') + ylab('Proportion in 5 km around sites') +
  scale_x_discrete(labels = scales::wrap_format(10)) + theme_bw() + labs(title = "Landcover Proportions")

ggsave("percentage_of_regional_richness__output__som_landcover_proportions.jpg")
```

```{r}
ggarrange(
  ggplot(merlin, aes(y = elevation_delta)) + geom_boxplot() + xlab('Elevation Delta') + ylab('Average Metres in 5 km around sites') +
    scale_x_discrete(labels = scales::wrap_format(10)) + theme_bw(),
  ggplot(merlin, aes(y = mean_elevation)) + geom_boxplot() + xlab('Mean Elevation') + ylab('Average Metres in 5 km around sites') +
    scale_x_discrete(labels = scales::wrap_format(10)) + theme_bw()
)

ggsave("percentage_of_regional_richness__output__som_elevations.jpg")
```


------------------------------------------------------------------
Birdlife [300 or less checklists]: Difference in richness
------------------------------------------------------------------
```{r}
birdlife300 = birdlife[birdlife$number_of_checklists <= 300,]
nrow(birdlife300)
```

```{r, cache = TRUE}
blr300_richness_result <- model_average_richness(birdlife300)
blr300_richness_result
```


Cities ordered by response for hotspots with 300 or less checklists
```{r}
birdlife300_city_response <- create_city_dataset(birdlife300_mixed_model)
birdlife300_city_response = birdlife300_city_response[,c('name', 'response')]
names(birdlife300_city_response) = c('name', 'response_300_checklists')
birdlife300_city_response = left_join(birdlife300_city_response, birdlife_city_response[,c('name', 'response')])
birdlife300_city_response[order(birdlife300_city_response$response_300_checklists), c('name', 'response_300_checklists', 'response')]
```

Cities ordered by response for all hotspots
```{r}
birdlife300_city_response[order(birdlife300_city_response$response), c('name', 'response_300_checklists', 'response')]
```


```{r}
bl300_richness_sum <- model_summary('birdlife', 'richness', blr300_richness_result)
bl300_richness_sum
```

```{r}
birdlife300_richness_plot <- bl300_richness_sum[bl300_richness_sum$model == 'full',]

birdlife300_richness_plot$explanatory <- factor(birdlife300_richness_plot$explanatory, levels = c('closed_forest', 'open_forest', 'shrubs', 'herbaceous_vegetation', 'herbaceous_wetland', 'permanent_water', 'cultivated', 'urban', 'mean_elevation_scaled', 'elevation_delta_scaled', 'realmAfrotropic', 'realmAustralasia', 'realmIndomalayan', 'realmNearctic', 'realmNeotropic'))
birdlife300_richness_plot$type <- 'Proportion of landcover\n5 km around site'
birdlife300_richness_plot$type[birdlife300_richness_plot$explanatory %in% c('mean_elevation_scaled', 'elevation_delta_scaled')] <- 'Scaled (0-1) average\nelevation 5 km around site'
birdlife300_richness_plot$type[birdlife300_richness_plot$explanatory %in% c('realmAfrotropic', 'realmAustralasia', 'realmIndomalayan', 'realmNearctic', 'realmNeotropic')] <- 'Realm'

birdlife300_plot = ggplot(birdlife300_richness_plot, aes(y=explanatory, x=richness_birdlife_estimate, colour = type)) + 
  geom_line() +
  geom_point()+
  geom_errorbar(aes(xmin=richness_birdlife_estimate-richness_birdlife_error, xmax=richness_birdlife_estimate+richness_birdlife_error), width=.2,
                 position=position_dodge(0.05)) +
  scale_y_discrete(
    limits = rev(levels(birdlife300_richness_plot$explanatory)), 
    labels = c('closed_forest' = 'Closed forest', 'open_forest' = 'Open forest', 'shrubs' = 'Shrubs', 'herbaceous_vegetation' = 'Herbaceous\nvegetation', 'herbaceous_wetland' = 'Herbaceous\nwetland', 'permanent_water' = 'Permanent\nwater', 'cultivated' = 'Cultivated', 'urban' = 'Urban', 'mean_elevation_scaled' = 'Mean elevation\nscaled', 'elevation_delta_scaled' = 'Elevation delta\nscaled', 'realmAfrotropic' = 'Afrotropical', 'realmAustralasia' = 'Austaliasian', 'realmIndomalayan' = 'Indomalayan', 'realmNearctic' = 'Nearctic', 'realmNeotropic' = 'Neotropical')) +
  theme_bw() +
  geom_vline(xintercept=0, linetype="dotted") +
  guides(colour=guide_legend(title="Predictor type")) + xlab('Increase in proportion of regional pool richness\n± Standard Error') + ylab('Predictor') +
  theme(legend.justification = "top")
birdlife300_plot
ggsave('percentage_of_regional_richness__output__birdlife_richness_300_checklists_or_less_result.jpg')
```


------------------------------------------------------------------
Birdlife [No Australasia]: Difference in richness
------------------------------------------------------------------
```{r}
birdlifeNoAustralia = birdlife[birdlife$realm != 'Australasia',]
nrow(birdlifeNoAustralia)
```

```{r, cache = TRUE}
blrNoAustralia_richness_result <- model_average_richness(birdlifeNoAustralia)
blrNoAustralia_richness_result
```


Cities ordered by response for hotspots with no australasia
```{r}
birdlifeNoAustralia_city_response <- create_city_dataset(birdlifeNoAustralia_mixed_model)
birdlifeNoAustralia_city_response = birdlifeNoAustralia_city_response[,c('name', 'response')]
names(birdlifeNoAustralia_city_response) = c('name', 'response_no_australasia')
birdlifeNoAustralia_city_response = left_join(birdlifeNoAustralia_city_response, birdlife_city_response[,c('name', 'response')])
birdlifeNoAustralia_city_response[order(birdlifeNoAustralia_city_response$response_no_australasia), c('name', 'response_no_australasia', 'response')]
```

Cities ordered by response for all hotspots
```{r}
birdlifeNoAustralia_city_response[order(birdlifeNoAustralia_city_response$response), c('name', 'response_no_australasia', 'response')]
```


```{r}
blNoAustralia_richness_sum <- model_summary('birdlife', 'richness', blrNoAustralia_richness_result)
blNoAustralia_richness_sum
```

```{r}
birdlifeNoAustralia_richness_plot <- blNoAustralia_richness_sum[blNoAustralia_richness_sum$model == 'full',]

birdlifeNoAustralia_richness_plot$explanatory <- factor(birdlifeNoAustralia_richness_plot$explanatory, levels = c('closed_forest', 'open_forest', 'shrubs', 'herbaceous_vegetation', 'herbaceous_wetland', 'permanent_water', 'cultivated', 'urban', 'mean_elevation_scaled', 'elevation_delta_scaled', 'realmAfrotropic', 'realmAustralasia', 'realmIndomalayan', 'realmNearctic', 'realmNeotropic'))
birdlifeNoAustralia_richness_plot$type <- 'Proportion of landcover\n5 km around site'
birdlifeNoAustralia_richness_plot$type[birdlifeNoAustralia_richness_plot$explanatory %in% c('mean_elevation_scaled', 'elevation_delta_scaled')] <- 'Scaled (0-1) average\nelevation 5 km around site'
birdlifeNoAustralia_richness_plot$type[birdlifeNoAustralia_richness_plot$explanatory %in% c('realmAfrotropic', 'realmAustralasia', 'realmIndomalayan', 'realmNearctic', 'realmNeotropic')] <- 'Realm'

birdlifeNoAustralia_plot = ggplot(birdlifeNoAustralia_richness_plot, aes(y=explanatory, x=richness_birdlife_estimate, colour = type)) + 
  geom_line() +
  geom_point()+
  geom_errorbar(aes(xmin=richness_birdlife_estimate-richness_birdlife_error, xmax=richness_birdlife_estimate+richness_birdlife_error), width=.2,
                 position=position_dodge(0.05)) +
  scale_y_discrete(
    limits = rev(levels(birdlifeNoAustralia_richness_plot$explanatory)), 
    labels = c('closed_forest' = 'Closed forest', 'open_forest' = 'Open forest', 'shrubs' = 'Shrubs', 'herbaceous_vegetation' = 'Herbaceous\nvegetation', 'herbaceous_wetland' = 'Herbaceous\nwetland', 'permanent_water' = 'Permanent\nwater', 'cultivated' = 'Cultivated', 'urban' = 'Urban', 'mean_elevation_scaled' = 'Mean elevation\nscaled', 'elevation_delta_scaled' = 'Elevation delta\nscaled', 'realmAfrotropic' = 'Afrotropical', 'realmAustralasia' = 'Austaliasian', 'realmIndomalayan' = 'Indomalayan', 'realmNearctic' = 'Nearctic', 'realmNeotropic' = 'Neotropical')) +
  theme_bw() +
  geom_vline(xintercept=0, linetype="dotted") +
  guides(colour=guide_legend(title="Predictor type")) + xlab('Increase in proportion of regional pool richness\n± Standard Error') + ylab('Predictor') +
  theme(legend.justification = "top")
birdlifeNoAustralia_plot
ggsave('percentage_of_regional_richness__output__birdlife_richness_no_australia.jpg')
```

------------------------------------------------------------------
Birdlife [No Afrotropics]: Difference in richness
------------------------------------------------------------------
```{r}
birdlifeNoAfrica = birdlife[birdlife$realm != 'Afrotropic',]
nrow(birdlifeNoAfrica)
```

```{r, cache = TRUE}
blrNoAfrica_richness_result <- model_average_richness(birdlifeNoAfrica)
blrNoAfrica_richness_result
```


Cities ordered by response for hotspots with no afrotropics
```{r}
birdlifeNoAfrica_city_response <- create_city_dataset(birdlifeNoAfrica_mixed_model)
birdlifeNoAfrica_city_response = birdlifeNoAfrica_city_response[,c('name', 'response')]
names(birdlifeNoAfrica_city_response) = c('name', 'response_no_africa')
birdlifeNoAfrica_city_response = left_join(birdlifeNoAfrica_city_response, birdlife_city_response[,c('name', 'response')])
birdlifeNoAfrica_city_response[order(birdlifeNoAfrica_city_response$response_no_africa), c('name', 'response_no_africa', 'response')]
```

Cities ordered by response for all hotspots
```{r}
birdlifeNoAfrica_city_response[order(birdlifeNoAfrica_city_response$response), c('name', 'response_no_africa', 'response')] 
```


```{r}
blNoAfrica_richness_sum <- model_summary('birdlife', 'richness', blrNoAfrica_richness_result)
blNoAfrica_richness_sum
```

```{r}
birdlifeNoAfrica_richness_plot <- blNoAfrica_richness_sum[blNoAfrica_richness_sum$model == 'full',]

birdlifeNoAfrica_richness_plot$explanatory <- factor(birdlifeNoAfrica_richness_plot$explanatory, levels = c('closed_forest', 'open_forest', 'shrubs', 'herbaceous_vegetation', 'herbaceous_wetland', 'permanent_water', 'cultivated', 'urban', 'mean_elevation_scaled', 'elevation_delta_scaled', 'realmAfrotropic', 'realmAustralasia', 'realmIndomalayan', 'realmNearctic', 'realmNeotropic'))
birdlifeNoAfrica_richness_plot$type <- 'Proportion of landcover\n5 km around site'
birdlifeNoAfrica_richness_plot$type[birdlifeNoAfrica_richness_plot$explanatory %in% c('mean_elevation_scaled', 'elevation_delta_scaled')] <- 'Scaled (0-1) average\nelevation 5 km around site'
birdlifeNoAfrica_richness_plot$type[birdlifeNoAfrica_richness_plot$explanatory %in% c('realmAfrotropic', 'realmAustralasia', 'realmIndomalayan', 'realmNearctic', 'realmNeotropic')] <- 'Realm'

birdlifeNoAfrica_plot = ggplot(birdlifeNoAfrica_richness_plot, aes(y=explanatory, x=richness_birdlife_estimate, colour = type)) + 
  geom_line() +
  geom_point()+
  geom_errorbar(aes(xmin=richness_birdlife_estimate-richness_birdlife_error, xmax=richness_birdlife_estimate+richness_birdlife_error), width=.2,
                 position=position_dodge(0.05)) +
  scale_y_discrete(
    limits = rev(levels(birdlifeNoAfrica_richness_plot$explanatory)), 
    labels = c('closed_forest' = 'Closed forest', 'open_forest' = 'Open forest', 'shrubs' = 'Shrubs', 'herbaceous_vegetation' = 'Herbaceous\nvegetation', 'herbaceous_wetland' = 'Herbaceous\nwetland', 'permanent_water' = 'Permanent\nwater', 'cultivated' = 'Cultivated', 'urban' = 'Urban', 'mean_elevation_scaled' = 'Mean elevation\nscaled', 'elevation_delta_scaled' = 'Elevation delta\nscaled', 'realmAfrotropic' = 'Afrotropical', 'realmAustralasia' = 'Austaliasian', 'realmIndomalayan' = 'Indomalayan', 'realmNearctic' = 'Nearctic', 'realmNeotropic' = 'Neotropical')) +
  theme_bw() +
  geom_vline(xintercept=0, linetype="dotted") +
  guides(colour=guide_legend(title="Predictor type")) + xlab('Increase in proportion of regional pool richness\n± Standard Error') + ylab('Predictor') +
  theme(legend.justification = "top")
birdlifeNoAfrica_plot
ggsave('percentage_of_regional_richness__output__birdlife_richness_no_africa.jpg')
```

------------------------------------------------------------------
Birdlife [No Afrotropics and no Australisia]: Difference in richness
------------------------------------------------------------------
```{r}
birdlifeNeitherAfrNorAus = birdlife[birdlife$realm != 'Afrotropic' & birdlife$realm != 'Australasia',]
nrow(birdlifeNeitherAfrNorAus)
```

```{r, cache = TRUE}
blrNAA_richness_result <- model_average_richness(birdlifeNeitherAfrNorAus)
blrNAA_richness_result
```


```{r}
blNAA_richness_sum <- model_summary('birdlife', 'richness', blrNAA_richness_result)
blNAA_richness_sum
```

```{r}
birdlifeNAA_richness_plot <- blNAA_richness_sum[blNAA_richness_sum$model == 'full',]

birdlifeNAA_richness_plot$explanatory <- factor(birdlifeNAA_richness_plot$explanatory, levels = c('closed_forest', 'open_forest', 'shrubs', 'herbaceous_vegetation', 'herbaceous_wetland', 'permanent_water', 'cultivated', 'urban', 'mean_elevation_scaled', 'elevation_delta_scaled', 'realmAfrotropic', 'realmAustralasia', 'realmIndomalayan', 'realmNearctic', 'realmNeotropic'))
birdlifeNAA_richness_plot$type <- 'Proportion of landcover\n5 km around site'
birdlifeNAA_richness_plot$type[birdlifeNAA_richness_plot$explanatory %in% c('mean_elevation_scaled', 'elevation_delta_scaled')] <- 'Scaled (0-1) average\nelevation 5 km around site'
birdlifeNAA_richness_plot$type[birdlifeNAA_richness_plot$explanatory %in% c('realmAfrotropic', 'realmAustralasia', 'realmIndomalayan', 'realmNearctic', 'realmNeotropic')] <- 'Realm'

birdlifeNAA_plot = ggplot(birdlifeNAA_richness_plot, aes(y=explanatory, x=richness_birdlife_estimate, colour = type)) + 
  geom_line() +
  geom_point()+
  geom_errorbar(aes(xmin=richness_birdlife_estimate-richness_birdlife_error, xmax=richness_birdlife_estimate+richness_birdlife_error), width=.2,
                 position=position_dodge(0.05)) +
  scale_y_discrete(
    limits = rev(levels(birdlifeNAA_richness_plot$explanatory)), 
    labels = c('closed_forest' = 'Closed forest', 'open_forest' = 'Open forest', 'shrubs' = 'Shrubs', 'herbaceous_vegetation' = 'Herbaceous\nvegetation', 'herbaceous_wetland' = 'Herbaceous\nwetland', 'permanent_water' = 'Permanent\nwater', 'cultivated' = 'Cultivated', 'urban' = 'Urban', 'mean_elevation_scaled' = 'Mean elevation\nscaled', 'elevation_delta_scaled' = 'Elevation delta\nscaled', 'realmAfrotropic' = 'Afrotropical', 'realmAustralasia' = 'Austaliasian', 'realmIndomalayan' = 'Indomalayan', 'realmNearctic' = 'Nearctic', 'realmNeotropic' = 'Neotropical')) +
  theme_bw() +
  geom_vline(xintercept=0, linetype="dotted") +
  guides(colour=guide_legend(title="Predictor type")) + xlab('Increase in proportion of regional pool richness\n± Standard Error') + ylab('Predictor') +
  theme(legend.justification = "top")
birdlifeNAA_plot
ggsave('percentage_of_regional_richness__output__birdlife_richness_no_africa_nor_australisia.jpg')
```


------------------------------------------------------------------
Birdlife [Urban Only]: Difference in richness
------------------------------------------------------------------
```{r}
birdlife$urban_rounded = floor(birdlife$urban * 10) / 10
ggplot(birdlife, aes(x = urban_rounded)) + geom_bar()
```
```{r}
birdlifeHigherUrban = birdlife[birdlife$urban > 0.2,]
nrow(birdlifeHigherUrban)
```

```{r, cache = TRUE}
blrHigherUrban_richness_result <- model_average_richness(birdlifeHigherUrban)
blrHigherUrban_richness_result
```


```{r}
blrHigherUrban_richness_sum <- model_summary('birdlife', 'richness', blrHigherUrban_richness_result)
blrHigherUrban_richness_sum
```

```{r}
birdlifeHR_richness_plot <- blrHigherUrban_richness_sum[blrHigherUrban_richness_sum$model == 'full',]

birdlifeHR_richness_plot$explanatory <- factor(birdlifeHR_richness_plot$explanatory, levels = c('closed_forest', 'open_forest', 'shrubs', 'herbaceous_vegetation', 'herbaceous_wetland', 'permanent_water', 'cultivated', 'urban', 'mean_elevation_scaled', 'elevation_delta_scaled', 'realmAfrotropic', 'realmAustralasia', 'realmIndomalayan', 'realmNearctic', 'realmNeotropic'))
birdlifeHR_richness_plot$type <- 'Proportion of landcover\n5 km around site'
birdlifeHR_richness_plot$type[birdlifeHR_richness_plot$explanatory %in% c('mean_elevation_scaled', 'elevation_delta_scaled')] <- 'Scaled (0-1) average\nelevation 5 km around site'
birdlifeHR_richness_plot$type[birdlifeHR_richness_plot$explanatory %in% c('realmAfrotropic', 'realmAustralasia', 'realmIndomalayan', 'realmNearctic', 'realmNeotropic')] <- 'Realm'

birdlifeHR_plot = ggplot(birdlifeHR_richness_plot, aes(y=explanatory, x=richness_birdlife_estimate, colour = type)) + 
  geom_line() +
  geom_point()+
  geom_errorbar(aes(xmin=richness_birdlife_estimate-richness_birdlife_error, xmax=richness_birdlife_estimate+richness_birdlife_error), width=.2,
                 position=position_dodge(0.05)) +
  scale_y_discrete(
    limits = rev(levels(birdlifeHR_richness_plot$explanatory)), 
    labels = c('closed_forest' = 'Closed forest', 'open_forest' = 'Open forest', 'shrubs' = 'Shrubs', 'herbaceous_vegetation' = 'Herbaceous\nvegetation', 'herbaceous_wetland' = 'Herbaceous\nwetland', 'permanent_water' = 'Permanent\nwater', 'cultivated' = 'Cultivated', 'urban' = 'Urban', 'mean_elevation_scaled' = 'Mean elevation\nscaled', 'elevation_delta_scaled' = 'Elevation delta\nscaled', 'realmAfrotropic' = 'Afrotropical', 'realmAustralasia' = 'Austaliasian', 'realmIndomalayan' = 'Indomalayan', 'realmNearctic' = 'Nearctic', 'realmNeotropic' = 'Neotropical')) +
  theme_bw() +
  geom_vline(xintercept=0, linetype="dotted") +
  guides(colour=guide_legend(title="Predictor type")) + xlab('Increase in proportion of regional pool richness\n± Standard Error') + ylab('Predictor') +
  theme(legend.justification = "top")
birdlifeHR_plot
ggsave('percentage_of_regional_richness__output__birdlife_richness_higher_urban.jpg')
```

------------------------------------------------------------------
Birdlife [Check pseudoreplication]: Difference in richness
------------------------------------------------------------------

```{r}
locality_samples = read_csv('percentage_of_regional_richness__input__sampled_localities_min_distance_500m.csv')
table(locality_samples$SAMPLE_ID)
```


```{r}
plot_sample = function(sample_id) {
  birdlife_sample0 = birdlife[birdlife$locality_id %in% locality_samples$LOCALITY_ID[locality_samples$SAMPLE_ID == sample_id],]
  
  birdlife_sample0_richness_result <- model_average_richness(birdlife_sample0)
  birdlife_sample0_richness_summary <- model_summary('birdlife', 'richness', birdlife_sample0_richness_result)
  
  birdlife_sample0_richness_plot <- birdlife_sample0_richness_summary[birdlife_sample0_richness_summary$model == 'full',]
  
  birdlife_sample0_richness_plot$explanatory <- factor(birdlife_sample0_richness_plot$explanatory, levels = c('closed_forest', 'open_forest', 'shrubs', 'herbaceous_vegetation', 'herbaceous_wetland', 'permanent_water', 'cultivated', 'urban', 'mean_elevation_scaled', 'elevation_delta_scaled', 'realmAfrotropic', 'realmAustralasia', 'realmIndomalayan', 'realmNearctic', 'realmNeotropic'))
  birdlife_sample0_richness_plot$type <- 'Proportion of landcover\n5 km around site'
  birdlife_sample0_richness_plot$type[birdlife_sample0_richness_plot$explanatory %in% c('mean_elevation_scaled', 'elevation_delta_scaled')] <- 'Scaled (0-1) average\nelevation 5 km around site'
  birdlife_sample0_richness_plot$type[birdlife_sample0_richness_plot$explanatory %in% c('realmAfrotropic', 'realmAustralasia', 'realmIndomalayan', 'realmNearctic', 'realmNeotropic')] <- 'Realm'
  
  birdlifeSample0_plot = ggplot(birdlife_sample0_richness_plot, aes(y=explanatory, x=richness_birdlife_estimate, colour = type)) + 
    geom_line() +
    geom_point()+
    geom_errorbar(aes(xmin=richness_birdlife_estimate-richness_birdlife_error, xmax=richness_birdlife_estimate+richness_birdlife_error), width=.2,
                   position=position_dodge(0.05)) +
    scale_y_discrete(
      limits = rev(levels(birdlife_sample0_richness_plot$explanatory)), 
      labels = c('closed_forest' = 'Closed forest', 'open_forest' = 'Open forest', 'shrubs' = 'Shrubs', 'herbaceous_vegetation' = 'Herbaceous\nvegetation', 'herbaceous_wetland' = 'Herbaceous\nwetland', 'permanent_water' = 'Permanent\nwater', 'cultivated' = 'Cultivated', 'urban' = 'Urban', 'mean_elevation_scaled' = 'Mean elevation\nscaled', 'elevation_delta_scaled' = 'Elevation delta\nscaled', 'realmAfrotropic' = 'Afrotropical', 'realmAustralasia' = 'Austaliasian', 'realmIndomalayan' = 'Indomalayan', 'realmNearctic' = 'Nearctic', 'realmNeotropic' = 'Neotropical')) +
    theme_bw() +
    geom_vline(xintercept=0, linetype="dotted") +
    guides(colour=guide_legend(title="Predictor type")) + xlab('Increase in proportion of regional pool richness\n± Standard Error') + ylab('Predictor') +
    theme(legend.justification = "top")
  birdlifeSample0_plot
}
```

```{r}
plot_sample('0')
ggsave('percentage_of_regional_richness__output__birdlife_locality_sample0.jpg')
```

```{r}
plot_sample('1')
ggsave('percentage_of_regional_richness__output__birdlife_locality_sample1.jpg')
```


```{r}
plot_sample('2')
ggsave('percentage_of_regional_richness__output__birdlife_locality_sample2.jpg')
```

```{r}
plot_sample('3')
ggsave('percentage_of_regional_richness__output__birdlife_locality_sample3.jpg')
```

```{r}
plot_sample('4')
ggsave('percentage_of_regional_richness__output__birdlife_locality_sample4.jpg')
```

```{r}
plot_sample('5')
ggsave('percentage_of_regional_richness__output__birdlife_locality_sample5.jpg')
```

```{r}
plot_sample('6')
ggsave('percentage_of_regional_richness__output__birdlife_locality_sample6.jpg')
```

```{r}
plot_sample('7')
ggsave('percentage_of_regional_richness__output__birdlife_locality_sample7.jpg')
```

```{r}
plot_sample('8')
ggsave('percentage_of_regional_richness__output__birdlife_locality_sample8.jpg')
```

```{r}
plot_sample('9')
ggsave('percentage_of_regional_richness__output__birdlife_locality_sample9.jpg')
```
